# Generated by Django 6.0.7 on 2026-07-16 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at', None)), fields=('book_copy',), name='one_borrow_per_copy_unless_returned'),
        ),
    ]
