# Generated by Django 6.0.7 on 2026-07-17 08:42

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_isbn'),
        ('borrowing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrowing',
            name='one_borrow_per_copy_unless_returned',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='renewal_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrowed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('book_copy',), name='one_borrow_per_copy_unless_returned'),
        ),
    ]
