# Generated by Django 6.0.7 on 2026-07-17 08:42

import book.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^(?:\\d{9}[\\dX]|\\d{13})$', message='Insert only the correct ISBN with numbers'), django.core.validators.MinLengthValidator(10, message='ISBN is typically 10-13 digits'), book.models.validate_ISBN]),
        ),
    ]
